inp-charte:
  type: Web
  author: (Toulouse INP)
  title: Identité visuelle
  url: https://www.inp-toulouse.fr
actimage-charte:
  type: Web
  author: Actimage
  title: Identité visuelle
  url: https://www.actimage.com
wiki-onacvg:
  type: Web
  author: Contributeurs de Wikipédia
  title: Office national des combattants et des victimes de guerre
  url: https://fr.wikipedia.org/wiki/Office_national_des_combattants_et_des_victimes_de_guerre
no-verify:
  type: Web
  title: Manpage Git - Section git-commit
  author: Linus Torvalds
  url: https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-verify
java-var:
  type: Web
  title: Local Variable Type Inference
  author: Oracle
  url: https://docs.oracle.com/en/java/javase/21/language/local-variable-type-inference.html
cpp-auto:
  type: Web
  title: Placeholder type specifiers
  author: cppreference.com contributors
  url: https://cppreference.com/cpp/language/auto
